services:
  apache:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kdi-kominfo-app
    restart: unless-stopped
    ports:
      - "8006:80"
      - "5173:5173"
    volumes:
      - ./:/var/www/html
    networks:
      - shared-mysql-net

networks:
  shared-mysql-net:
    external: true
